# Generated by Django 5.2.4 on 2025-08-01 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('11:00-12:00', '11:00 AM - 12:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM')], max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('number_of_dogs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Group Walk Booking',
                'verbose_name_plural': 'Group Walk Bookings',
                'ordering': ['-booking_date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='IndividualWalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('number_of_dogs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(help_text='Preferred time (Note: 10AM-1PM and 2PM-5PM are not available due to group walks)', max_length=100)),
                ('reason_for_individual', models.TextField(help_text='Why does your dog need to be walked alone? (In training, non-sociable, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response to customer', null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('confirmed_time', models.CharField(blank=True, max_length=100, null=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Individual Walk Request',
                'verbose_name_plural': 'Individual Walk Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWalkSlotManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_slot_available', models.BooleanField(default=True, help_text='11am-12pm slot')),
                ('afternoon_slot_available', models.BooleanField(default=True, help_text='3pm-4pm slot')),
                ('morning_slot_capacity', models.IntegerField(default=6)),
                ('afternoon_slot_capacity', models.IntegerField(default=6)),
                ('notes', models.TextField(blank=True, help_text='Admin notes for this date', null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('allergies', models.TextField(blank=True, help_text='Any allergies or health concerns', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special care instructions', null=True)),
                ('good_with_other_dogs', models.BooleanField(default=True)),
                ('behavioral_notes', models.TextField(blank=True, help_text='Any behavioral concerns', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_walk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='home.groupwalk')),
                ('individual_walk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='home.individualwalk')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
