# Generated by Django 5.2.4 on 2025-08-01 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vet_address',
            field=models.TextField(default=django.utils.timezone.now, help_text='Vet practice address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='vet_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of your vet practice', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='vet_phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='Vet practice phone number', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupwalk',
            name='customer_postcode',
            field=models.CharField(default=django.utils.timezone.now, help_text='We serve within 10 miles of Croyde, North Devon', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualwalk',
            name='customer_postcode',
            field=models.CharField(default=django.utils.timezone.now, help_text='We serve within 10 miles of Croyde, North Devon', max_length=10),
            preserve_default=False,
        ),
    ]
