# Generated by Django 5.2.4 on 2025-08-07 12:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dog_vet_address_dog_vet_name_dog_vet_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupwalkslotmanager',
            options={'ordering': ['date'], 'verbose_name': 'Group Walk Slot Manager', 'verbose_name_plural': 'Group Walk Slot Managers'},
        ),
        migrations.AlterUniqueTogether(
            name='groupwalkslotmanager',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupwalkslotmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupwalkslotmanager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='behavioral_notes',
            field=models.TextField(blank=True, help_text='Any behavioral concerns, triggers, or special handling requirements', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_other_dogs',
            field=models.BooleanField(default=True, help_text='Important for group walks - uncheck if your dog has issues with other dogs'),
        ),
        migrations.AlterField(
            model_name='groupwalk',
            name='customer_postcode',
            field=models.CharField(help_text='We serve within 10 miles of Croyde, North Devon (EX31-EX34 postcodes)', max_length=10),
        ),
        migrations.AlterField(
            model_name='groupwalk',
            name='number_of_dogs',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='afternoon_slot_available',
            field=models.BooleanField(default=True, help_text='3:00 PM - 4:00 PM slot available'),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='afternoon_slot_capacity',
            field=models.IntegerField(default=4, help_text='Maximum dogs for afternoon slot (0-6)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='morning_slot_available',
            field=models.BooleanField(default=True, help_text='11:00 AM - 12:00 PM slot available'),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='morning_slot_capacity',
            field=models.IntegerField(default=4, help_text='Maximum dogs for morning slot (0-6)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes for this date (holiday, weather, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='individualwalk',
            name='customer_postcode',
            field=models.CharField(help_text='We serve within 10 miles of Croyde, North Devon (EX31-EX34 postcodes)', max_length=10),
        ),
    ]
