# Generated by Django 5.2.4 on 2025-08-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_groupwalkslotmanager_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwalk',
            name='time_slot',
            field=models.CharField(choices=[('11:00-12:00', '11:00 AM - 12:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM')], max_length=30),
        ),
    ]
