# Generated by Django 5.2.4 on 2025-08-11 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_groupwalk_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwalkslotmanager',
            name='evening_slot_available',
            field=models.BooleanField(default=True, help_text='6:00 PM - 8:00 PM slot available'),
        ),
        migrations.AddField(
            model_name='groupwalkslotmanager',
            name='evening_slot_capacity',
            field=models.IntegerField(default=4, help_text='Maximum dogs for evening slot (0-6)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='groupwalk',
            name='time_slot',
            field=models.CharField(choices=[('10:00-12:00', '10:00 AM - 12:00 PM'), ('14:00-16:00', '2:00 PM - 4:00 PM'), ('18:00-20:00', '6:00 PM - 8:00 PM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='afternoon_slot_available',
            field=models.BooleanField(default=True, help_text='2:00 PM - 4:00 PM slot available'),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='morning_slot_available',
            field=models.BooleanField(default=True, help_text='10:00 AM - 12:00 PM slot available'),
        ),
        migrations.AlterField(
            model_name='individualwalk',
            name='preferred_time',
            field=models.CharField(help_text='Preferred time (Note: 9AM-1PM, 1PM-5PM and 5PM-9PM are not available due to group walks)', max_length=100),
        ),
    ]
