# Generated by Django 5.2.4 on 2025-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_groupwalkslotmanager_evening_slot_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwalk',
            name='customer_postcode',
            field=models.CharField(help_text='We serve within 10 miles of Croyde, North Devon (EX31-EX34 postcodes)', max_length=20),
        ),
        migrations.AlterField(
            model_name='individualwalk',
            name='customer_postcode',
            field=models.CharField(help_text='We serve within 10 miles of Croyde, North Devon (EX31-EX34 postcodes)', max_length=20),
        ),
    ]
