# Generated by Django 5.2.4 on 2025-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_groupwalk_customer_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwalk',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Groups multiple bookings made together', max_length=50, null=True),
        ),
    ]
