# Generated by Django 5.2.4 on 2025-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_groupwalk_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwalk',
            name='time_slot',
            field=models.CharField(choices=[('09:30-11:30', '09:30 AM - 11:30 PM'), ('14:00-16:00', '2:00 PM - 4:00 PM'), ('18:00-20:00', '6:00 PM - 8:00 PM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='morning_slot_available',
            field=models.BooleanField(default=True, help_text='09:30 AM - 11:30 PM slot available'),
        ),
        migrations.AlterField(
            model_name='individualwalk',
            name='preferred_time',
            field=models.CharField(help_text='Preferred time (Note: 8.30AM-12.30PM, 1PM-5PM and 5PM-9PM are not available due to group walks)', max_length=100),
        ),
    ]
