# Generated by Django 5.2.4 on 2025-10-02 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_groupwalk_time_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_weekend_bookings', models.BooleanField(default=True, help_text='Allow bookings on Saturdays and Sundays')),
                ('max_dogs_per_booking', models.IntegerField(default=4, help_text='Maximum dogs allowed per group walk booking.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('allow_evening_slot', models.BooleanField(default=True, help_text='Allow bookings for 6:00 PM - 8:00PM evening slot.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
    ]
