# Generated by Django 5.2.4 on 2025-10-02 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwalk',
            name='number_of_dogs',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
