# Generated by Django 5.2.4 on 2025-11-13 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_groupwalk_number_of_dogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupwalkslotmanager",
            name="afternoon_slot_capacity",
            field=models.IntegerField(
                default=4,
                help_text="⚠️ NOTE: This is ignored for availability calculations. Global max from Booking Settings is always used. This field is kept for reference only.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="groupwalkslotmanager",
            name="evening_slot_capacity",
            field=models.IntegerField(
                default=4,
                help_text="⚠️ NOTE: This is ignored for availability calculations. Global max from Booking Settings is always used. This field is kept for reference only.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="groupwalkslotmanager",
            name="morning_slot_capacity",
            field=models.IntegerField(
                default=4,
                help_text="⚠️ NOTE: This is ignored for availability calculations. Global max from Booking Settings is always used. This field is kept for reference only.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
