# Generated by Django 5.2.4 on 2026-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_groupwalkslotmanager_afternoon_slot_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupwalk',
            name='time_slot',
            field=models.CharField(choices=[('09:30-11:30', '09:30 AM - 11:30 AM'), ('14:00-16:00', '2:00 PM - 4:00 PM'), ('18:00-20:00', '6:00 PM - 8:00 PM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='groupwalkslotmanager',
            name='morning_slot_available',
            field=models.BooleanField(default=True, help_text='09:30 AM - 11:30 AM slot available'),
        ),
    ]
